apiVersion: cd.qdrant.io/v2
kind: HelmRelease
metadata:
  name: podinfo-gitrepository
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
