apiVersion: cd.qdrant.io/v2
kind: HelmRelease
metadata:
  name: podinfo-ocirepository
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: podinfo
  test:
    enable: true
  values:
    replicaCount: 2
